### ISSUE TITLE
How do I add a new language?

### ISSUE THREAD

**Issue by com2ghz** [sameersbn/docker-invoiceplane#10]
I'm new to Docker and want to run Invoiceplane in Docker. How can I add my own language to Invoiceplane?

**Comment by sameersbn** [comment]
@com2ghz Sorry for my late reply. 
You should submit your translations to the upstream project @ https://github.com/InvoicePlane/InvoicePlane

You may find additional relevant information in https://wiki.invoiceplane.com/en/1.5/system/translation-localization
