### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by karneaud** [sameersbn/docker-invoiceplane#7]
Tried to run your image using the supplied compose.xml and got the following on startup

> mysql_1         | Installing database...
> mysql_1         | Starting MySQL server...
> invoiceplane_1  | standard_init_linux.go:178: exec user process caused "no such file or directory"
> nginx_1         | standard_init_linux.go:178: exec user process caused "no such file or directory"
> wipayinvoiceplane_invoiceplane_1 exited with code 1
> wipayinvoiceplane_nginx_1 exited with code 1
> nginx_1         | standard_init_linux.go:178: exec user process caused "no such file or directory"
> nginx_1         | standard_init_linux.go:178: exec user process caused "no such file or directory"
> nginx_1         | standard_init_linux.go:178: exec user process caused "no such file or directory"
> invoiceplane_1  | standard_init_linux.go:178: exec user process caused "no such file or directory"
> invoiceplane_1  | standard_init_linux.go:178: exec user process caused "no such file or directory"
> invoiceplane_1  | standard_init_linux.go:178: exec user process caused "no such file or directory"
> invoiceplane_1  | standard_init_linux.go:178: exec user process caused "no such file or directory"
> nginx_1         | standard_init_linux.go:178: exec user process caused "no such file or directory"
> wipayinvoiceplane_invoiceplane_1 exited with code 1
> nginx_1         | standard_init_linux.go:178: exec user process caused "no such file or directory"
> invoiceplane_1  | standard_init_linux.go:178: exec user process caused "no such file or directory"
> invoiceplane_1  | standard_init_linux.go:178: exec user process caused "no such file or directory"

Not sure what that means ....is it a file/ directory permission?

**Comment by sameersbn** [comment]
@karneaud Sorry for not responding earlier.
Are you still facing this issue?

**Comment by karneaud** [comment]
switched to invoiceninja
